### ISSUE TITLE
question: how to generate these files.

### ISSUE THREAD

**Issue by mwpcheung** [ichitaso/iOS10.1.1-iphoneheaders#1]
hey there, I have found that your iOS headers is the most completely files.
1.  I want to know how did you generate these files.  would you please tell me how to gernate them by my self。 
2. I want to dump the whole iOS dyldcache ，to get  the whole binarys。 I have tried many opensrc tools all of them failed。
for axample dyld-deacache dyld extractor

**Comment by ichitaso** [comment]
I'm using limneos's classdump-dyld.
https://github.com/limneos/classdump-dyld
